---
title: "Conflict's Impact on Life Expectancy and Hale"
subtitle: ""
author: Andreas Handel
date: "`r Sys.Date()`"
format:
  docx:
    toc: false
    number-sections: true
    highlight-style: github
bibliography: ../assets/dataanalysis-references.bib
csl: ../assets/apa.csl
---


```{r, echo=FALSE, message=FALSE}
# load a few R packages
library(here)
library(knitr)
```


Part 1

Briefly describe what the data is, how it was collected, where you will get (or got) it from. How many observations do you have, what was measured? Anything else important to report about the data?

Life expectancy and HALE from IHME (https://ghdx.healthdata.org/record/ihmde-data/gbd-2019-life-expectancy-HALE-1990-2019), Conflict deaths from Uppsala (https://ucdp.uu.se/downloads/), Crime from UN (http://data.un.org)

IHME collects reports to model the life expectancy for 204 countries from 1990-2019
Uppsala contains data related to multiple different defined conflicts from 1946-2022
UN Crime data contains intentional homicides and other crimes for years 2005, 2010, 2015, 2021 


Explain the question you want to answer using the data. What will be your outcome(s) of interest (if any)? What (if any) specific predictors will you focus on? What relations/patterns are you looking for in the data?

A brief literature review suggests there is a stagnation in the life expectancy for working age men within Venezuela due to increased homicides. I'm interested in looking at the changes in conflict and crime, and if there is a relationship with the Healthy Life Expectancy calculated by IHME. 


As much as you know, suggest how you will analyze it. At this stage in the course, we haven’t covered analysis approaches yet, so you can keep things vague and non-technical here.

First I'd like to assess the models and data. Determine if I'm able to view all data from an age adjusted perspective. Then assess trends related to time. Lastly, I'd aline the life expectancy, crime, conflict timelines with historical events that have occured. If I could include migration data that would be an interesting covariate, but it is a known confounder and I'm not sure how to approach it. 

You are allowed, but not yet required, to provide background information for the question you plan to answer. For instance you can describe why it’s an interesting question, who else has done similar analyses, how your analysis will be new/different, etc. Similar to what you read in an introduction to a research paper. For the final report, you’ll need these parts. For part 1, they are not required, but you are welcome to already write down some of that.

For the past year, I've done literature reviews and a case study about the relationship between conflict and public health. As it stands, globally conflict measurements are not included as a risk or as a mortlaity/morbidity measurement within the IHME HALE due to "inconsitency". This is applicable for short situtations or events, but this doesn't account for the impact in long term events such. Venezuela has been in a consistent degression as it relates to world power, economic benefits, and public health. When viewing the country through IHME database, it was until the last couple years conflict and refugee status as been discussed as it pertains to Venezuela. 


Eventually, for your final report, what you write for this part will go into different sections of the full report. Some will go into the introduction, some in the methods section. You can already place these items there, or for now just write them as a single section.



